version: '3.8'

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile.flask
    container_name: covid_flask_app
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - ADMIN_PASSWORD=Vikash09
      - SECRET_KEY=covid19-prediction-secret
      - DB_PATH=/app/data/predictions.db
    volumes:
      - covid_db_volume:/app/data
    restart: always

  streamlit-app:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: covid_streamlit_app
    ports:
      - "8501:8501"
    environment:
      - PORT=8501
      - DB_PATH=/app/data/covid_health.db
    volumes:
      - covid_db_volume:/app/data
    restart: always

volumes:
  covid_db_volume:
    driver: local
